# Generated by Django 5.1.1 on 2024-10-04 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='started_programming',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
