# Generated by Django 5.1.1 on 2024-10-04 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0002_infomodel_started_programming'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
