# Generated by Django 5.1.1 on 2024-10-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0003_infomodel_created_at_infomodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategorymodel',
            name='description',
            field=models.TextField(default="It's good one"),
            preserve_default=False,
        ),
    ]
