# Generated by Django 5.1.1 on 2024-10-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0004_skillcategorymodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategorymodel',
            name='icon_class_name',
            field=models.CharField(default='fa-solid fa-python', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pages_app.skillcategorymodel'),
        ),
    ]
